name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --trace on

      # 🔹 Publicar resumen del reporte en la interfaz de GitHub Actions
      - name: Publicar resumen del reporte HTML
        if: always()
        run: |
          echo "## 📊 Playwright Test Report" >> $GITHUB_STEP_SUMMARY
          echo "[Haz clic aquí para ver el reporte completo.](playwright-report/index.html)" >> $GITHUB_STEP_SUMMARY

      # 🔹 Subir los artefactos (reportes + traces)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
            **/trace.zip
          retention-days: 30
